### PR TITLE
update insecure Gems loofah + rails-html-sanitizer

### PR DESCRIPTION
**Pull request by dominic**

### CODE REVIEW

**Comment by dominic** [comment]
PTAL @kyleschmolze

**Comment by kyleschmolze** [comment]
Interesting. I was under the impression that you're always supposed to make version upgrades in `Gemfile`, and then let bundle figure out the dependency tree and create `Gemfile.lock`, and never write to `Gemfile.lock` directly. Is that incorrect?

I was able to get the same results by adding these two lines to the `Gemfile`:

```
gem 'loofah', '>= 2.2.2'
gem 'rails-html-sanitizer', '= 1.0.4'
```

And then running `bundle update rails-html-sanitizer`, `bundle update loofah`, and then a final `bundle` just in case. My `Gemfile.lock` has the updated versions of the 2 gems, as well as a couple other upgrades due to their dependencies. Do you think this is a better approach? Take a look at #118

**Comment by dominic** [comment]
It's totally okay to update `Gemfile.lock` for really specific dependencies. This post captures how I tend to approach updates pretty well: https://makandracards.com/makandra/13885-how-to-update-a-single-gem-conservatively

If we don't want to hand-update `Gemfile.lock`, I'd prefer a `bundle update GEMNAME` before adding `loofah` and `rails-html-sanitizer` as explicit dependencies as in #118. Since our app doesn't directly call features from those two gems, I tend to lean away from writing them into the `Gemfile` itself.

**Comment by kyleschmolze** [comment]
Hold up, travis is failing. Trying to fix.

**Comment by dominic** [comment]
Oops. We both just did the same change! Sorry; I force pushed in confusion.

**Pull request merged**
