### PR TITLE
Use presigned URLs for S3 upload.

### PR DESCRIPTION
**Pull request by bcipriano**
Issue https://github.com/eastbaydsa/website/issues/41.

The test S3 bucket now has correct permissions - all objects public readable, writes only through presigned URLs.

This is working but isn't quite ready for review yet - it depends on https://github.com/eastbaydsa/website/pull/42 which needs to be merged first.

### CODE REVIEW

**Comment by dominic** [comment]
Sorry for blocking #42 on review; do you want eyes on this now that it's landed?

**Comment by bcipriano** [comment]
No worries! I needed to do a final merge from main but yes this is ready for review now!

**Comment by bcipriano** [comment]
Definitely, I'll merge this soon and push to Heroku so others can try it out - it's working great for me but I wouldn't be at all surprised to find this needs a bit more tweaking.

I can generate personal keys through my IAM account but I think I'll need you to generate and send me AWS key/secrets from the main account. Maybe two so we can keep staging and prod totally separate?

**Comment by dominic** [comment]
Rad - let me get you some staging keys via Slack.

**Comment by dominic** [comment]
Oh actually, I can just add them to the Heroku app. They're all set for https://dashboard.heroku.com/apps/eastbaydsa-website-staging/settings

**Comment by bcipriano** [comment]
Perfect, thanks!

**Pull request merged**
