### PR TITLE
Layout support for slightly wider navigation

### PR DESCRIPTION
**Pull request by dominic**
While we figure out information architecture and longer term navigation, we had a feature request from the SC to support the previous site’s navigation for now. 

This change:

* Shrinks the logo earlier at tablet size instead of mobile
* Decreases space between menu items
* Slightly increases max-width for site

### CODE REVIEW

**Comment by dominic** [comment]
Before:
screen shot 2018-06-27 at 8 59 13 am

---

After:
screen shot 2018-06-27 at 8 59 25 am

**Comment by dominic** [comment]
@kyleschmolze PTAL

**Comment by kyleschmolze** [comment]
Looks great. Couple things:

1. This is a pretty busy navbar at this point, but I understand that it's hard to de-prioritize any particular item when "but everything is important!" Not a huge deal. There are some tablet sizes that will display a bit awkwardly, but I'm not really worried about it. Who's really on a tablet anyways? E.g:
image




2. I personally feel that Join + Donate should be the left-most 2 options. I don't care which one takes the coveted left-most spot, I'd personally lean towards Join by 20%. What do @sarmaswe + @wesholing think? (This is a decision made in the Production database, however, so doesn't affect this merge)

**Comment by dominic** [comment]
My goal is for us to cut it down again. I think right now, it's just hard to remove "News" and "Resources" without a coherent plan to get at that information at the top level. Additions like dropdown menus and a redesign information architecture would be huge improvements eventually. 

Controversial opinion, but I don't think "About" deserves top-level treatment anymore. The homepage and footer should highlight "what is this org?", but for navigating our site, I think it's a much lower priority for getting at information.

**Pull request merged**
