### PR TITLE
Join page

### LINKED ISSUE #114: Build a Join page
Right now, the join page has many components:

1. A link to the nice "Renew" page someone put together: http://renew.eastbaydsa.org/
2. A link to the National DSA join page (https://act.dsausa.org/donate/membership/). 
3. A link to our events calendar
4. A form to sign up for our newsletter

Which of these are we trying to recreate? All of them? I feel that the most important aspect of the join page is to rope them into the local chapter, while explaining that they won't officially be a member until they join via national. But since there's a ~2 month delay between signing up for national and us knowing about it, I'd rather focus on getting them involved / subscribed asap, and officially signed up secondarily.

Thoughts?

### PR DESCRIPTION
**Pull request by kyleschmolze**
Here's a first stab at a simple join page according to the convo in #114. Happy to accept edits on this!

technical note: I had to hard-code this page, which means I had to hard-code the tags for it's sign up form. If I remember correctly, `eb_supporter` is a good default, so that's what I put, but let me know!

technical note no. 2: this is actually branched off of `visual-update`, so once that gets merged you'll see that I only changed a few files.

Closes #114 

Screenshot for feedback!
screenshot-2018-5-17 east bay dsa

cc @dominic @sarmaswe

### CODE REVIEW

**Comment by sarmaswe** [comment]
I like it a lot -- no feedback. 

@wesholing @dominic, will you take a look as well?

**Comment by dominic** [comment]
Just to dig into what's going on here - this is a hardcoded form because we want to have content _after_ the form, which isn't possible in the current page structure? I'm wondering if there's anything else we can do to address that.

**Comment by dominic** [comment]
Alternatively, I created a "Join" page using our existing page structure at: https://eastbaydsa-website-staging.herokuapp.com/join

Coupled with https://github.com/eastbaydsa/website/pull/123, those `<h3>` links can be displayed as buttons instead.

**Comment by kyleschmolze** [comment]
I know that it seems silly to hard-code one page just because we want the form earlier in the page, but I do think that the email signup form should come before official membership. It's way lower commitment, and is generally the first step I assume most people will reasonably take when getting involved with EBDSA. 

Obviously this could merit a much longer discussion on overall new-member experience and onboarding, but personally I'd rather keep the hard-coded version for now until we make those decisions.

**Pull request merged**
