### PR TITLE
Calendar integration - add individual events or subscribe to all

### LINKED ISSUE #146: Add "Add to Google Calendar" link
I modified the event template a while back to auto-generate an "Add to Google Calendar" link to event pages. Could we keep that, too? It's basically just a dynamically generated URL string that pulls event data already on the page (but only if the necessary data is on the page).

### PR DESCRIPTION
**Pull request by kyleschmolze**
Add an individual event to your calendar:
screen shot 2018-06-26 at 3 04 56 pm

Subscribe to all events on the main calendar page (this is below the calendar). Also, if you've filtered by tags, you can add a subscription which only includes those events:

screen shot 2018-06-26 at 3 12 35 pm

I put the links on the event page in a small unobtrusive place, but happy to reconsider where those live. Also, there are a couple different ways to do this, and some of them have browser dependencies. For example, Firefox on iOS doesn't seem to be able to open `.ics` files, so it can't directly import 1 event to the Calendar app, but Safari does. The subscription URL should work everywhere, but I haven't tested on Android. The Google Calendar links should work everywhere cause it's just a URL to calendar.google.com with the details pre-filled.

Closes #146

### CODE REVIEW

**Comment by dominic** [comment]
We might want to take out the "subscribe to a filtered calendar link" (and all filtering) before launch if we can't agree on our NationBuilder tags with Sean in time, but this is a really cool trick, and lets us hand out links to "subscribe to our electoral calendar" 👨‍🍳

**Comment by kyleschmolze** [comment]
Yeah it was more of a fancy add-on that turned out to be easy to build so I included it. I agree that if we're not settled on tags then it's not super useful or worth pushing just yet. I'll comment it out and merge.

**Comment by kyleschmolze** [comment]
Ok I actually commented out all tags, as you suggest. No tags on events#index, no tags on events#show. Super easy to turn back on when we make that call with Sean.

**Comment by dominic** [comment]
Awesome. Glad it's just commented, because I do want to turn em back on soon.

**Pull request merged**
