### PR TITLE
Nav accessibility updates

### PR DESCRIPTION
**Pull request by llkats**
To jump into the codebase and get acquainted, I ran an accessibility audit and started fixing up a few issues that the audit flagged.

~*Note*: this is not well tested yet because I'm not sure how to log into the CMS yet, so my local nav menu is empty right now. Will update once I've tested more thoroughly.~ Tested and looks good ✔️ 

**Changes**
- add lang to html tag
- use <nav> element in header for the nav
- add aria attributes; label the hamburger menu
- add js to toggle expanded state/aria attribute
- add role to header__menu

### CODE REVIEW

**Comment by dominic** [comment]
:eyes:

**Comment by dominic** [comment]
This looks great to me with the nav :+1:

**Comment by kyleschmolze** [comment]
This looks great, but I would say it'd be smart to test it with some menu items before we merge! Just import the Admin in `db/seeds.rb` with `rake db:setup`, or copy paste the code into a console, and then log in using that username / password on `localhost:3000/admin`. You can then create some menu items and see how they look!

**Comment by llkats** [comment]
Hooray, I got logged in locally and recreated production's nav menu items, and I'm feeling confident now about these changes. I do want to note that there is now a focus ring on the hamburger menu icon when it is active. Generally this is considered a win for accessibility, but sometimes people have strong feels about the aesthetics of the focus ring, so I do want to call that out before I merge. Anyone have any objections?

image

**Comment by dominic** [comment]
No objection from me there - I think it's good for hamburgers especially to give em a little focus state like that. For form fields I might suggest we do a custom one to keep colors consistent, but this is :+1:

**Comment by kyleschmolze** [comment]
Looks great!

**Pull request merged**
